version: '3'

volumes:
  postgres_data: { }
  ch_data: { }

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=web
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=transactions
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi:
    build:
      dockerfile: Dockerfile
      context: "."
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  transaction_handler:
    build:
      dockerfile: Dockerfile
      context: "."
    entrypoint:
      - python3
      - transaction_handler.py
    depends_on:
      - postgres
